In [3]:
import numpy as np
from scipy.sparse import csr_matrix

# Valores no cero de la matriz
data = [3, 4, 5, 5, 8]

# Índices de las columnas donde están los valores no cero
indices = [0, 0, 5, 0, 2]

# Punteros de las filas (indica el comienzo de cada fila en 'data')
indptr = [0, 1, 2, 2, 2, 2, 3, 5, 5]

# Crear la matriz en formato CSR
A_csr = csr_matrix((data, indices, indptr), shape=(8, 8))

# Imprimir la matriz completa
print("Matriz:")
print(A_csr.toarray())

# Mostrar los componentes del formato CSR
print("\nValores (data):", A_csr.data)
print("Índices de columna (indices):", A_csr.indices)
print("Punteros de fila (indptr):", A_csr.indptr)



Matriz:
[[3 0 0 0 0 0 0 0]
 [4 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 5 0 0]
 [5 0 8 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

Valores (data): [3 4 5 5 8]
Índices de columna (indices): [0 0 5 0 2]
Punteros de fila (indptr): [0 1 2 2 2 2 3 5 5]
